USE IndexLab;
GO
SET STATISTICS PROFILE ON;
SET STATISTICS IO ON;
GO
SELECT QuoteId, COUNT(*) AS Views, AVG(DurationMs) AS AvgDurationMs
FROM   QuoteViews
WHERE  QuoteId = 42
GROUP BY QuoteId;
GO
SET STATISTICS PROFILE OFF;
SET STATISTICS IO OFF;
GO